### ISSUE TITLE
Can we remove "gulpIgnore.include('*.js')"

### ISSUE THREAD

**Issue by stephanedemotte** [joecohens/laravel-elixir-webpack#15]
Hi !

Can we remove line 30 

```
.pipe(gulpIgnore.include('*.js'))

```

I use ExtractTextPlugin to extract CSS, but this line ignore my file

Thanks !

**Comment by joecohens** [comment]
Sorry for the delay. I'm fixing some issues now, I'll let you know once it's done.

**Comment by joecohens** [comment]
Done https://github.com/joecohens/laravel-elixir-webpack/commit/9d9546c9cb49d8a59cef599cd91986faf252659c
