### ISSUE TITLE
watch all files in js

### ISSUE THREAD

**Issue by vanderlin** [joecohens/laravel-elixir-webpack#9]
https://github.com/joecohens/laravel-elixir-webpack/blob/master/index.js#L36
`.watch(config.get('assets.js.folder') + '/**/*');`

**Comment by fitz7** [comment]
this would be great.

**Comment by joecohens** [comment]
Sorry for the delay! I didn't saw the notification :(. Yeah I think this would be useful. I will also change the config.get to the options so that the folder can be configured easily

**Comment by joecohens** [comment]
This should be added in https://github.com/joecohens/laravel-elixir-webpack/commit/44e0bea186b744fa5e1cfc8da39bbaa198a577d9 thanks for the recommendation and if you have any trouble let me know :)

**Comment by browncolyn** [comment]
Not sure why you would watch all files. Why isn't this a config option like the way other elixir plugins work? For example, here's how you change the watch path for sass:

```
// gulpfile.js
elixir.Task.find('sass').watch('./resources/**/*.+(sass|scss)')
```
